### PR TITLE
fix: update `got`

### PR DESCRIPTION
**Pull request by SimenB**
For https://github.com/advisories/GHSA-pfrx-2q88-qq97

### CODE REVIEW

**Comment by sindresorhus** [comment]
Got 11 requires Node.js 10. This package requires Node.js 8.

**Comment by SimenB** [comment]
can we drop node 8, then? I know 99,999999% of these audit reports are complete bullshit, but they're still noisy and annoying 🙁

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/norway-postal-codes/releases/tag/v4.0.0

**Comment by SimenB** [comment]
Thank you!

**Pull request closed without merging**
